### ISSUE TITLE
Use List of Views instead of Strings?

### ISSUE THREAD

**Issue by K232** [robinmanuelthiel/swipecards#6]
Hi Robin,
thanks for this cool plugin! I try to use a list of Views instead of just strings as I want to design my cards individually per card. Unfortunately I don't get it to work. Would it be possible to use a list of Views? How could I do that?
Many thanks in advance!

**Comment by AndreiMisiukevich** [comment]
Hi @K232 
You can check this https://github.com/AndreiMisiukevich/CardView
both cardsview and carouselview

**Comment by K232** [comment]
Yes, already had a look there, thanks for the link!
My problem currently is: I need a carousel with lazy loading as I have dozens of pages to show. Additionally the carousel should be updatable while it's displayed, but unfortunately I did not find a working solution yet.
Have a nice weekend!
