### ISSUE TITLE
Single card is not visible

### ISSUE THREAD

**Issue by marcgrosy** [robinmanuelthiel/swipecards#7]
Hello,
Thanks for your great component.
I have an issue when I have a single card. 
I see cards only if I have 2 or more.

Marc

**Comment by robinmanuelthiel** [comment]
Oh yep, I can confirm that. Thanks for filing the bug. Working on it for the next release!

**Comment by robinmanuelthiel** [comment]
Fixed in the latest release 0.3.2.
https://www.nuget.org/packages/Forms.Controls.SwipeCards/0.3.2
